### Test for creating a journal entry
POST http://localhost:8080/journal-entries
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1eWVuQGdtYWlsLmNvbSIsImlhdCI6MTc4MzUxMDYyMiwiZXhwIjoxNzgzNTE0MjIyfQ.yjbHEH6JNOZSYFTowUcpIYSGw6NVoeEAUH6Z0JT0sIc
Content-Type: application/json

{
    "journalContent": "Hôm nay học Validation",
    "noteToSelf": "Hoàn thành Aura",
    "tags": ["happy", "healthy", "study"]
}

### Test for retrieving a journal entry by ID
GET http://localhost:8080/journal-entries/14

### Test for retrieving all journal entries
GET http://localhost:8080/journal-entries?page=0&size=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1eWVuQGdtYWlsLmNvbSIsImlhdCI6MTc4MzUxMDYyMiwiZXhwIjoxNzgzNTE0MjIyfQ.yjbHEH6JNOZSYFTowUcpIYSGw6NVoeEAUH6Z0JT0sIc

### Test for updating a journal entry
PUT http://localhost:8080/journal-entries/1
Content-Type: application/json

{
    "journalContent": "Hôm nay học Spring Boot - Cập nhật",
    "noteToSelf": "Hoàn thành Aura - Cập nhật",
    "tags": []
}

### Test for deleting a journal entry
DELETE http://localhost:8080/journal-entries/3

### Test for retrieving side-quests by emotion
GET http://localhost:8080/side-quests/emotion/SAD

### Test for retrieving side-quests
GET http://localhost:8080/side-quests

### Test for creating a journal entry
POST http://localhost:8080/journal-entries
Content-Type: application/json

{
    "journalContent": "Hôm nay học Validation",
    "noteToSelf": "Hoàn thành Aura",
    "tags": ["happy", "healthy", "study"]
}

### Test for retrieving a journal entry by ID
GET http://localhost:8080/journal-entries/32
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4Mjk4MTY4OCwiZXhwIjoxNzgyOTg1Mjg4fQ._fLxGRLFwLKSDuif8z5yWtJh8HXwp_Eex-C3NNRSBBQ
### Test for retrieving all journal entries
GET http://localhost:8080/journal-entries
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4Mjk4MTY4OCwiZXhwIjoxNzgyOTg1Mjg4fQ._fLxGRLFwLKSDuif8z5yWtJh8HXwp_Eex-C3NNRSBBQ

### Test for updating a journal entry
PUT http://localhost:8080/journal-entries/32
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4Mjk4MTY4OCwiZXhwIjoxNzgyOTg1Mjg4fQ._fLxGRLFwLKSDuif8z5yWtJh8HXwp_Eex-C3NNRSBBQ
Content-Type: application/json

{
    "journalContent": "Hôm nay học Spring Boot - Cập nhật",
    "noteToSelf": "Hoàn thành Aura - Cập nhật",
    "tags": []
}

### Test for deleting a journal entry
DELETE http://localhost:8080/journal-entries/33
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4Mjk4MTY4OCwiZXhwIjoxNzgyOTg1Mjg4fQ._fLxGRLFwLKSDuif8z5yWtJh8HXwp_Eex-C3NNRSBBQ

### Test for retrieving side-quests by emotion
GET http://localhost:8080/side-quests/emotion/SAD

### Test for retrieving side-quests
GET http://localhost:8080/side-quests

### Test for register
POST https://aurasystem-production-5536.up.railway.app/auth/register
Content-Type: application/json

{
    "fullName": "Hoàng Uyên",
    "email": "uyen@gmail.com",
    "password": "12345678"
}

### Test for login
POST https://aurasystem-production-5536.up.railway.app/auth/login
Content-Type: application/json

{
    "email": "uyen@gmail.com",
    "password": "12345678"
}

### Test for authentication by JWT
GET http://localhost:8080/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MjczNjkwMywiZXhwIjoxNzgyNzQwNTAzfQ.nAzuajkSkZcoKqpyoYLZTGxKtsu2cTCVxWvxhgP2GmY

### Refresh Token
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MjczOTQwMiwiZXhwIjoxNzgzMzQ0MjAyfQ.x1LPq0ixWkC0JhJCH2yZ6fz_6qdsd-R60o0auTXE1Lw"
}

### Logout
POST http://localhost:8080/auth/logout
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MjczOTQwMiwiZXhwIjoxNzgzMzQ0MjAyfQ.x1LPq0ixWkC0JhJCH2yZ6fz_6qdsd-R60o0auTXE1Lw"
}

### Test for creating a side quest for a user
POST http://localhost:8080/user-side-quests
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4Mjk4NDEwNCwiZXhwIjoxNzgyOTg3NzA0fQ.e0B1cMG62U2o5f1Ca_H6HoOGrfAK_FQ3EPEs7QIqXPg
Content-Type: application/json

{
    "sideQuestId": 5
}

### Test for retrieving all user side quests
GET http://localhost:8080/user-side-quests
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4Mjk4NDEwNCwiZXhwIjoxNzgyOTg3NzA0fQ.e0B1cMG62U2o5f1Ca_H6HoOGrfAK_FQ3EPEs7QIqXPg

#### Login Test
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"123"
}

### Test for completing a user side quest
PATCH http://localhost:8080/user-side-quests/16/complete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MzI4MjI4NCwiZXhwIjoxNzgzMjg1ODg0fQ.hwC1U9Ho5on3OT2WMcxsa6nYmIbFEpOAqnSfz65VY-A
Content-Type: application/json

#### Test for retrieving completed user side quests
GET http://localhost:8080/user-side-quests/completed
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MzI4MjI4NCwiZXhwIjoxNzgzMjg1ODg0fQ.hwC1U9Ho5on3OT2WMcxsa6nYmIbFEpOAqnSfz65VY-A

###
GET http://localhost:8080/streak
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MzI2ODMzNCwiZXhwIjoxNzgzMjcxOTM0fQ.4tfiEUScpxrys2WvAlt3uBz-NrITMQpvS-NHoACKStE

###
GET http://localhost:8080/level
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MzI4MTQxMywiZXhwIjoxNzgzMjg1MDEzfQ.Y7WKeLjnZvKi4klSC6iI-SFHSiDmrPO7bjBxlSvHuAE

### Test information of user
GET http://localhost:8080/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MzM0MzE1MSwiZXhwIjoxNzgzMzQ2NzUxfQ.8jPVuQb_my_jP7pwP6WbowmonXshK0xqdi0WZsdongk

### Test Update Profile
PUT http://localhost:8080/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MzMxMjM4OSwiZXhwIjoxNzgzMzE1OTg5fQ.l-12y0qruqahxHH03XISSM2c75L15bANVWjYs-sbv54
Content-Type: application/json

{
    "fullName":"Nguyen Van A",
    "avatarUrl":"https://abc.com/avatar.jpg"
}

### Test change password
PUT http://localhost:8080/users/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MzQ4MTk0NCwiZXhwIjoxNzg0MDg2NzQ0fQ.P8NAM4gf4EDPzHt54Ykpv4Q1ODsk2cCvgaCFK5HOitc
Content-Type: application/json

{
    "currentPassword": "87654321",
    "newPassword": "12345678"
}

### Test
GET http://localhost:8080/inspiration-prompts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MzQ4MTk0NCwiZXhwIjoxNzg0MDg2NzQ0fQ.P8NAM4gf4EDPzHt54Ykpv4Q1ODsk2cCvgaCFK5HOitc

###
GET http://localhost:8080/inspiration-prompts/random?limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MzQ4MTk0NCwiZXhwIjoxNzg0MDg2NzQ0fQ.P8NAM4gf4EDPzHt54Ykpv4Q1ODsk2cCvgaCFK5HOitc