package org.example.aurabackend.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Persistence model for the structured information extracted from a journal
 * entry by the LLM (Milestone 2+).
 *
 * One row per journal entry — enforced by the UNIQUE constraint on
 * journal_entry_id at the database level.
 *
 * SECURITY CONTRACT:
 *   rawLlmResponse is stored for audit and debugging only.
 *   It must NEVER appear in any DTO, API response, or JSON serialisation.
 *   All DTOs must explicitly exclude this field.
 *
 * Entity Design Rule:
 *   This class is a persistence model only. It must not contain business
 *   logic, scoring calculations, or trigger detection. Those belong in
 *   ExtractionService and UserActivityStatsService (Milestone 2).
 */
@Entity
@Table(name = "journal_extractions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class JournalExtraction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The journal entry this extraction belongs to.
     * UNIQUE at DB level — one extraction per journal entry.
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "journal_entry_id", nullable = false, unique = true)
    private JournalEntry journalEntry;

    /**
     * Denormalised user reference for efficient pagination queries on
     * GET /users/me/extractions without joining through journal_entries.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // ─── Structured extraction fields ────────────────────────────────────────
    // All stored as JSONB arrays. Nullable because extraction may be partial
    // if the LLM returns incomplete output.

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private List<String> activities;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private List<String> places;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private List<String> people;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "positive_triggers", columnDefinition = "jsonb")
    private List<String> positiveTriggers;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "negative_triggers", columnDefinition = "jsonb")
    private List<String> negativeTriggers;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "future_plans", columnDefinition = "jsonb")
    private List<String> futurePlans;

    /** One-sentence contextual summary generated by the LLM. */
    @Column(columnDefinition = "TEXT")
    private String moodContext;

    // ─── Audit fields ─────────────────────────────────────────────────────────

    /**
     * Full raw LLM JSON response.
     *
     * AUDIT / DEBUG ONLY.
     * This field must NEVER be included in any DTO or API response.
     * Access is restricted to direct database queries by administrators.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "raw_llm_response", columnDefinition = "jsonb")
    private String rawLlmResponse;

    /** Name and version of the model that produced this extraction. */
    @Column(name = "extraction_model", length = 100)
    private String extractionModel;

    @Column(name = "extracted_at", nullable = false, updatable = false)
    private LocalDateTime extractedAt;

    @PrePersist
    public void prePersist() {
        if (extractedAt == null) {
            extractedAt = LocalDateTime.now();
        }
    }
}
