spring.application.name=aura-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/aura_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.signerKey=AURA_SECRET_KEY_2026_SUPER_SECRET_KEY_123456789
jwt.valid-duration=3600
jwt.refresh-duration=604800

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web.cors=TRACE