package org.example.aurabackend.dto.response;

import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Public API response DTO for a journal extraction.
 *
 * SECURITY CONTRACT:
 *   This DTO deliberately omits the following fields from JournalExtraction:
 *     - rawLlmResponse  (AUDIT ONLY — must never leave the backend)
 *     - extractionModel (internal operational metadata)
 *
 *   If this DTO is ever modified, confirm that rawLlmResponse is still absent.
 *
 * Consumed by:
 *   GET /journal-entries/{id}/extraction
 */
@Data
@Builder
public class JournalExtractionResponse {

    private Long id;

    /** ID of the journal entry this extraction belongs to. */
    private Long journalEntryId;

    // ─── Structured extraction fields ────────────────────────────────────────

    private List<String> activities;

    private List<String> places;

    private List<String> people;

    private List<String> positiveTriggers;

    private List<String> negativeTriggers;

    private List<String> futurePlans;

    /** One-sentence contextual summary generated by the LLM. */
    private String moodContext;

    private LocalDateTime extractedAt;
}
